const express = require("express");
const router = express.Router();
const modules = require("../modules");
const schemas = require("../schema/schema");
const verifyToken = require("../middleware/verifyToken");
const { validateschema } = require("../middleware/validateschema");
router.post("/register", validateschema(schemas.resister), modules.register);
router.get("/profile", verifyToken, modules.getuserdata);
router.post("/login", modules.login);
router.get("/logout", verifyToken, modules.logout);
module.exports = router;
